'use client'

import { useState, useEffect, useRef, useCallback } from 'react'
import { createClient } from '@/lib/supabase/client'
import ChartDisplay from '@/components/chart/ChartDisplay'
import Header from '@/components/layout/Header'
import type { ChartMode } from '@/components/chart/ChartDisplay'

// All astrology interpretation columns generated by /api/interpret
const ASTRO_COLUMNS = [
  'interp_lagna',
  'interp_sun', 'interp_moon', 'interp_mercury', 'interp_venus',
  'interp_mars', 'interp_jupiter', 'interp_saturn',
  'interp_uranus', 'interp_neptune', 'interp_pluto',
  'interp_rahu', 'interp_ketu',
  'interp_dignities', 'interp_mahadasha', 'interp_purusharthas',
]

interface NatalProductClientProps {
  chart: Record<string, unknown>
  tier:  number
}

function ProgressBar({ done, total }: { done: number; total: number }) {
  const pct = total > 0 ? Math.round((done / total) * 100) : 0
  return (
    <div
      style={{
        position:        'fixed',
        top:             0,
        left:            0,
        right:           0,
        zIndex:          50,
        backgroundColor: '#0e0c0b',
        borderBottom:    '1px solid rgba(154,124,46,0.2)',
        padding:         '10px 20px',
        display:         'flex',
        alignItems:      'center',
        gap:             '14px',
      }}
    >
      <div
        style={{
          flex:            1,
          height:          '3px',
          backgroundColor: 'rgba(154,124,46,0.15)',
          borderRadius:    '2px',
          overflow:        'hidden',
        }}
      >
        <div
          style={{
            height:          '100%',
            width:           `${pct}%`,
            backgroundColor: '#9a7c2e',
            borderRadius:    '2px',
            transition:      'width 0.4s ease',
          }}
        />
      </div>
      <span
        style={{
          fontFamily:    'var(--font-raleway, sans-serif)',
          fontSize:      '10px',
          fontWeight:    600,
          letterSpacing: '0.1em',
          color:         'rgba(154,124,46,0.7)',
          whiteSpace:    'nowrap',
        }}
      >
        {done} / {total} sections
      </span>
    </div>
  )
}

export default function NatalProductClient({ chart: initialChart, tier }: NatalProductClientProps) {
  const supabase = createClient()

  const [chart, setChart]   = useState<Record<string, unknown>>(initialChart)
  const [mode,  setMode]    = useState<ChartMode>('traditional')
  const [generating, setGenerating] = useState(false)
  const [done,  setDone]    = useState(0)
  const [total, setTotal]   = useState(0)

  const eventSourceRef = useRef<EventSource | null>(null)
  const chartIdRef     = useRef<string>(String(initialChart.id ?? ''))

  // Re-fetch the chart row from Supabase and merge into local state
  const refreshChart = useCallback(async () => {
    const { data } = await supabase
      .from('charts')
      .select('*')
      .eq('id', chartIdRef.current)
      .single()
    if (data) setChart(data as Record<string, unknown>)
  }, [supabase])

  useEffect(() => {
    const chartJson = initialChart.chart_json

    // Determine which astrology sections are already generated
    const missing = ASTRO_COLUMNS.filter(col => {
      const v = initialChart[col]
      return !v || typeof v !== 'string' || v.trim() === ''
    })

    if (missing.length === 0) return   // everything already done

    const skipColumns = ASTRO_COLUMNS.filter(c => !missing.includes(c))

    setGenerating(true)
    setTotal(missing.length)
    setDone(0)

    // Open SSE stream
    const body = JSON.stringify({
      chart_json:   chartJson,
      tier,
      chart_id:     chartIdRef.current,
      skip_columns: skipColumns,
    })

    // EventSource requires GET; we use fetch + ReadableStream instead
    let cancelled = false
    let completedCount = 0

    async function streamInterpret() {
      try {
        const res = await fetch('/api/interpret', {
          method:  'POST',
          headers: { 'Content-Type': 'application/json' },
          body,
        })

        if (!res.ok || !res.body) {
          setGenerating(false)
          return
        }

        const reader  = res.body.getReader()
        const decoder = new TextDecoder()
        let   buffer  = ''

        while (true) {
          const { done: streamDone, value } = await reader.read()
          if (streamDone || cancelled) break

          buffer += decoder.decode(value, { stream: true })
          const lines = buffer.split('\n')
          buffer = lines.pop() ?? ''

          for (const line of lines) {
            if (!line.startsWith('data: ')) continue
            try {
              const event = JSON.parse(line.slice(6)) as Record<string, unknown>

              if (event.done) {
                await refreshChart()
                if (!cancelled) setGenerating(false)
                return
              }

              if (event.status === 'done' || event.status === 'error') {
                completedCount++
                if (!cancelled) setDone(completedCount)
                // Refresh chart row so ChartDisplay shows new content
                await refreshChart()
              }
            } catch {
              // malformed SSE line — ignore
            }
          }
        }
      } catch (err) {
        console.error('[NatalProductClient] SSE error:', err)
      } finally {
        if (!cancelled) setGenerating(false)
      }
    }

    streamInterpret()

    return () => {
      cancelled = true
      eventSourceRef.current?.close()
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])   // run once on mount

  return (
    <>
      {generating && <ProgressBar done={done} total={total} />}
      <div style={{ paddingTop: generating ? '36px' : '0' }}>
        <Header />
        <ChartDisplay
          chart={chart}
          chartJson={chart.chart_json}
          tier={tier}
          mode={mode}
          onModeChange={setMode}
        />
      </div>
    </>
  )
}
